apiVersion: v1
kind: LimitRange
metadata:
  name: community
  labels:
    app: community
    tier: platform
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 200Mi
      default:
        cpu: 500m
        memory: 1000Mi
      min:
        cpu: 50m
        memory: 100Mi
      max:
        cpu: 500m
        memory: 1000Mi
